_wandb:
    value:
        cli_version: 0.21.0
        e:
            6ne0e5p0f5dwyd0lqf636p8e4opht4iy:
                codePath: Image-Segmentation/train_segformer.py
                codePathLocal: train_segformer.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1003753218048"
                        used: "310723354624"
                email: suraj.14xd@gmail.com
                executable: /home/suraj/anaconda3/envs/vision-2/bin/python
                git:
                    commit: dbaeef752046c5a084473a56657801d17883b62e
                    remote: https://github.com/SurajK-14/SCR-Progression.git
                gpu: NVIDIA GeForce GTX 1650 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 Ti
                      uuid: GPU-1752a634-5cea-d36a-c57c-ae1138470289
                host: dell
                memory:
                    total: "33252700160"
                os: Linux-6.11.0-29-generic-x86_64-with-glibc2.39
                program: /home/suraj/Git/SCR-Progression/Image-Segmentation/train_segformer.py
                python: CPython 3.11.13
                root: /home/suraj/Git/SCR-Progression/Image-Segmentation
                startedAt: "2025-07-14T22:18:27.347397Z"
                writerId: 6ne0e5p0f5dwyd0lqf636p8e4opht4iy
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "3":
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.44.1
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 8
device:
    value: cuda
epochs:
    value: 10
image_size:
    value: 512
layer_indices:
    value:
        - 0
        - 2
learning_rate:
    value: 0.0001
model_name:
    value: nvidia/mit-b0
num_test_samples:
    value: 70
num_train_samples:
    value: 500
